### ISSUE TITLE
Multiplayer Compatibility 

### ISSUE THREAD

**Issue by Ariakim-Taiyo** [Spice9/Geofs-Multiliveries#1]
Good day, you may know me as another developer for geofs, but if not that's fine lol.

A while back, i wrote a plugin for geofs that did essentially the same as yours, except for a wider range of aircraft. It was most well-known for the 737 ryanair livery. Some of these liveries were in fact multpilayer compatible, but only for those who were using the plugin as well; anyone not using the plugin would see a KLM livery in multiplayer.

The method uses an already existing feature in geofs designed for livery support in mp. 

You simply check the value of Object.values(multiplayer.visibleUsers)["index"].currentLivery and use that as a display base.

Here is some code that I used in my system to check all of the livery IDs of visible users:

*note that there are different implementations for 2.9 and 3.0*

**2.9:**
```js
  function updateMultiplayer(){
  Object.values(multiplayer.visibleUsers).forEach(function(e){
if (e.lastLivery != e.currentLivery){

    if (e.currentLivery == /*liveryIdHere*/){
     geofs.api.Model.prototype.changeTexture(/*"textureMapUrlHere"*/, 0, multiplayer.visibleUsers[e.id].model); 

    }
    e.lastLivery = e.currentLivery
  })
}
```

**3.0:**
```js
  function updateMultiplayer(){
  Object.values(multiplayer.visibleUsers).forEach(function(e){
if (e.lastLivery != e.currentLivery){

    if (e.currentLivery == /*liveryIdHere*/){
geofs.api.changeModelTexture(multiplayer.visibleUsers[e.id].model._model, /*"textureMapUrlHere"*/, 0);
    }
    e.lastLivery = e.currentLivery
  })
}
```

You can simply host your multiplayer texture files in the resolution of the multiplayer model textures, and then pass them as the url input.

It appears that you already post the new livery ids to the server with this plugin, so you just have to access and apply them.

Hope this helps!

**Comment by Spice9** [comment]
Oh thank you so much Ariakim I'll try it

**Comment by Spice9** [comment]
//Livery-4
var dropdown4 = document.createElement("li");
dropdown4.innerHTML = "Boeing 737 Max 8 (Alaska Airlines)"
    document.getElementsByClassName("geofs-aircraft-list")[0].appendChild(dropdown4);
    let dropdown4Settings = document.createElement("div");
dropdown4.setAttribute("onclick", 'geofs.aircraft.instance.loadLivery("4")');



 function updateMultiplayer(){
  Object.values(multiplayer.visibleUsers).forEach(function(e){
if (e.lastLivery != e.currentLivery){
    if (e.currentLivery == 4){
      geofs.api.loadModel("https://www.geo-fs.com/backend/aircraft/repository/test4_427352_4035/multiplayer.glb", 0, multiplayer.visibleUsers[e.id].model);
    }

}
   e.lastLivery = e.currentLivery
  })
}
I did try intergrating it but still doesn't work... have I intergrated it properly?

**Comment by Ariakim-Taiyo** [comment]
You need to call the function repeatedly in order for it to work. use setInterval() with a slow interval to avoid lag.

**Comment by Ariakim-Taiyo** [comment]
eg; 
```js
mpRefresh = setInterval(function(){
updateMultiplayer();
}, 5000)
```
