### ISSUE TITLE
I CAN HELP MAKE A 777-300ER AND I HAVE 3D MODELLED ALOT OF IT ALREADY

### ISSUE THREAD

**Issue by Ahnaf552** [Spice9/Geofs-Multiliveries#100]
I made a 777 300er in blender and i am working on the cockpit and if you can help like animation code other things it might JUST ACTUALLY WORK!!
LRX IS SOOOOOOO BAAD AT MAKING PLANES AND YOUR ONES FEEL SO NICE TO FLY.
I can butter landings with your plane but his planes just SMACK !!! right on the runway
and other people are requesting 777s and this might actually work just hear me out.

base like the fueselage wings and stuff like that are done but im working to make a cooler and more realistic cockpit .
p.s . I LOVE FLYING YOUR PLANES FOR HOURS AND HOURS NON -STOP

**Comment by iuhairways** [comment]
People are already making 2 777-200's
but can u send me model in Gltf or Glb

**Comment by Ahnaf552** [comment]
what should i send it to you on
i can give it to you through gmail
my gmail is ; ahnafadib44@gmail.com

**Comment by Ahnaf552** [comment]
> People are already making 2 777-200's but can u send me model in Gltf or Glb

What do you mean by 2 if you have one you can just make texture files for more

**Comment by Ahnaf552** [comment]
here is the gltf/ glb
https://github.com/Ahnaf552/Geo-fs-777-300er-by-Ahnaf44

**Comment by Spice9** [comment]
I'm not really gonna have much time to focus on geofs because my school is gonna begin shortly, so you could get help for the development of you 777 in this discord server https://discord.gg/Hpfjjp8V .

**Comment by Ahnaf552** [comment]
> 

Yes I understand thank you.

**Comment by CementAndRebar** [comment]
1: why are LRX planes so bad?
2: your model is... not that good. This is literally a model one would use as the far, low poly one in geofs. Makes my original B17 look actually good 💀

**Comment by Spice9** [comment]
to be fair though he is perhaps a beginner in blender, and he is making a 77W in his own will.....

**Comment by githubuser589** [comment]
> LRX IS SOOOOOOO BAAD AT MAKING PLANES

I really don’t think you have the right to say things like this when you haven’t even coded or released your plane yet.

**Comment by Ahnaf552** [comment]
> > LRX IS SOOOOOOO BAAD AT MAKING PLANES
> 
> I really don’t think you have the right to say things like this when you haven’t even coded or released your plane yet.

i just dont like his cockpit and you cant flare with his alot of his planes 
Mainly just wanted a better cockpit like the generic 737

**Comment by CementAndRebar** [comment]
You cant flare because you arent good enough. They have some of the best physics in the game, so its a skill issue

**Comment by ThatOneBestDoggo** [comment]
> LRX IS SOOOOOOO BAAD AT MAKING PLANES

> I really don’t think you have the right to say things like this when you haven’t even coded or released your plane yet.

> i just dont like his cockpit and you cant flare with his alot of his planes
Mainly just wanted a better cockpit like the generic 737

bro, elon is right, you cannot flare bc you're not good enough. the cockpit is not designed better bc people don't use cockpit mode that much. and what are you, comparing a first plane to a pro plane...

**Comment by Ahnaf552** [comment]
> > LRX IS SOOOOOOO BAAD AT MAKING PLANES
> 
> > I really don’t think you have the right to say things like this when you haven’t even coded or released your plane yet.
> 
> > i just dont like his cockpit and you cant flare with his alot of his planes
> > Mainly just wanted a better cockpit like the generic 737
> 
> bro, elon is right, you cannot flare bc you're not good enough. the cockpit is not designed better bc people don't use cockpit mode that much. and what are you, comparing a first plane to a pro plane...

He fixed it and i can flare and land his plane in cockpit view and how is that a pro plane 
And I use cockpit view because when I will be flying a real plane i will be in a cockpit not a game
The game dosent have all the parameters a real plane does


and im not arguing im just saying and i love your planes and this is not a offensive i hate you and u r wrong and i am right comment i just dont want to fly a air newzealand with a cockpit like that.

**Comment by Ahnaf552** [comment]
And why does everybody have hate comments with a negative tone
dont you guys want a better 777 with more liveries ???
I AM LITERALLY SO CONFUSED @ThatOneBestDoggo

**Comment by Ahnaf552** [comment]
I Have a video i made to show you guys that i can flare and his plane acts weird;
https://www.youtube.com/watch?v=_d-3MYNLRLo
AND PLEASE READ THE DESCRIPTION IT WILL MAKE ALOT SENSE AFTER

**Comment by Ariakim-Taiyo** [comment]
I've been informed of this dispute, and i've made a quick comparison with a more reputable simulator:
https://youtu.be/xNylIIf-7r4

As outlined in the video, the LRX 777 is *not* realistic when compared to the MSFS one. Whether the MSFS one is realistic or not is not within my analysis, since it is likely designed with better documentation anyway.

The LRX 777 is not as realistic as you all think. just because it handles like a dump truck doesn't mean it should show so many inconsistencies.

**Comment by Ariakim-Taiyo** [comment]
I could go on and compare his other aircraft with better simulators, but i would hope you get the point.
