### ISSUE TITLE
shiba and co a319 livery (for cammie cherta)

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#103]
https://i.ibb.co/RBtB3cV/SHBA319.jpg

**Comment by Spice9** [comment]
for the a319 liveries you have to send it to GT

**Comment by iuhairways** [comment]
oh ok

**Comment by ThatOneBestDoggo** [comment]
Fictional liveries probably won't work (as far as I'm aware). But it would make Camch happy.

**Comment by Spice9** [comment]
well... unless there isnt any issue with the space on the backend I would continue to accept fictional ones
