### ISSUE TITLE
Peak Air Airbus A320neo

### ISSUE THREAD

**Issue by srirae** [Spice9/Geofs-Multiliveries#108]
https://ibb.co/rG0PQY2

**Comment by Spice9** [comment]
added

**Comment by SrivamsiRajesh** [comment]
nvm i got it thanks

**Comment by srirae** [comment]
ohk thanks @Spice9 . But when I click on the text i cant import the plane to geofs . Like when I click the option AirbusneoA380 (PeakAir) By - Sri Vamsi Rajesh . I cant import the plane to fly

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/177586743-bc68575c-0324-4a03-b46f-9941111256ce.png)

It loads for me

**Comment by srirae** [comment]
Ohk my friend thought me how to do it i did not choose the multiframe nvm thanks tho have a great day
