### ISSUE TITLE
New livery 

### ISSUE THREAD

**Issue by Lachy-your-local-aussie** [Spice9/Geofs-Multiliveries#11]
RAAF livery for P-8I and qantas livery for 787-10

**Comment by Spice9** [comment]
I've made an US Navy livery for p8 and might add the RAAF one too . I will think about the Qantas 787 later
I am currently working on the a320

**Comment by Lachy-your-local-aussie** [comment]
when do you think it will be done

**Comment by Spice9** [comment]
RAAF p8 might be by tomorrow
