### ISSUE TITLE
BIMAN BANGLADESH 787-10

### ISSUE THREAD

**Issue by Ahnaf552** [Spice9/Geofs-Multiliveries#111]
https://ibb.co/st2ZWyG
Biman has 787-9 not 10s but I could not find the template
and THANK YOU SOO MUCH FOR MAKING the 737 it means alot
and your planes are the best (community contributed but you still beat the rest)

**Comment by Ahnaf552** [comment]
Oh and dont forget to make issues 101 and 107 from iuh first because you did not see his
:)

**Comment by Spice9** [comment]
added
