### ISSUE TITLE
787-9 DREAMLINER JAPAN AIRLINES

### ISSUE THREAD

**Issue by FGAIRLINES** [Spice9/Geofs-Multiliveries#112]
Can you add this? thank you!!!
https://ibb.co/W3kKxH9

**Comment by Ahnaf552** [comment]
Hey bro you have to invert the bottom one.
and besides that its perfect i will definitely fly with it

**Comment by ThatOneBestDoggo** [comment]
I have 2 issues that I want to address.
Issue 1: The bottom livery is not flipped. If not flipped, one side would be fine, and the other side would be just chaos.
Issue 2: For those people who are using this for flights and recording them, it would be a absolute pain to find out that you have cutted out a rectangle in a real plane's image and poorly putting it onto your livery. 
And yes. I'm a honest dude. Besides those 2 issues, yep, that would be a good livery.

**Comment by Ahnaf552** [comment]
Hey Bro I fixed it
I inverted the bottom one and got rid of the grey shade in the cut off rectangle so you should be fine and the livery is perfect
Anything thing for you.
here is the file https://ibb.co/tD11GHd
can you please edit your one on top with this link instead.
if you ever need anything you can tell me :)

**Comment by Spice9** [comment]
added

**Comment by FGAIRLINES** [comment]
Thanks for Spice 9, Ahnaf552 and ThatOneBestDoggo!!!
And in whic aircrafts is need to flip the bottom?
Thank you again!!!
