### ISSUE TITLE
Sri Lankan airlines kandyan perahera livery (concept)

### ISSUE THREAD

**Issue by SriLankanflyer** [Spice9/Geofs-Multiliveries#113]
https://ibb.co/BPsD38P                                      I think this is right but if did something wrong pls let me know and don't add it to it until I re-send it if its wrong

**Comment by ThatOneBestDoggo** [comment]
As far as I'm aware, that is not a real livery.
Fictional liveries used to be allowed, but it isn't now.
I'm just trying to help you, I don't think that livery is going to get in.

**Comment by SriLankanflyer** [comment]
I know its not a real livery I just saw it off a video thumbnail and I thought this it a good livery idea I was actually running put off ideas

**Comment by SriLankanflyer** [comment]
I meant out off

**Comment by ThatOneBestDoggo** [comment]
There's a ton of livery ideas I can do. Just know that this livery is not going to make it in though. 
How about the OneWorld livery for Sri Lankan?

**Comment by Spice9** [comment]
yes I think a oneworld livery would be better

**Comment by SriLankanflyer** [comment]
Ok I'll change it
