### ISSUE TITLE
ITA Airways A320 (Born in 2021 livery)

### ISSUE THREAD

**Issue by ThatOneBestDoggo** [Spice9/Geofs-Multiliveries#115]
Made by ThatOneBestDoggo.
https://ibb.co/WcSf0pq

**Comment by Spice9** [comment]
added 2 of ur liveries

**Comment by iuhairways** [comment]
what about mine?!

**Comment by ThatOneBestDoggo** [comment]
WOOOOOOOOOOOOOO THANK YOU SO MUCH

**Comment by Spice9** [comment]
> what about mine?!

The easyjet a319? I'll ask GT if he had uploaded that livery and once I get the number of the texture_ then I would add it

**Comment by iuhairways** [comment]
> > what about mine?!
> 
> The easyjet a319? I'll ask GT if he had uploaded that livery and once I get the number of the texture_ then I would add it

nonono the 737 euro wings

**Comment by FGAIRLINES** [comment]
I love ITA AIRWAYS
