### ISSUE TITLE
OneWorld Sri Lankan airlines A320neo

### ISSUE THREAD

**Issue by SriLankanflyer** [Spice9/Geofs-Multiliveries#117]
https://ibb.co/qkHJYmZ I hope this gets through and if any mistakes pls inform

**Comment by Ahnaf552** [comment]
its beautiful :)

**Comment by ThatOneBestDoggo** [comment]
Actual first time that I saw a decent livery. can't argue with this.

**Comment by SriLankanflyer** [comment]
Only problem is there is no A320 214 thing so this is somewhat wrong

**Comment by Spice9** [comment]
added

**Comment by SriLankanflyer** [comment]
thanks

**Comment by Spice9** [comment]
the code had an error but its fixed now

**Comment by SriLankanflyer** [comment]
thanks
