### ISSUE TITLE
A.I AIRWAYS (for a.is youtube)

### ISSUE THREAD

**Issue by Ahnaf552** [Spice9/Geofs-Multiliveries#121]
https://ibb.co/XV08DSH

**Comment by Ahnaf552** [comment]
https://www.youtube.com/channel/UCvS2SNAxCtuGHcFqh0KR-nQ
you know A.I so i guess thats for him

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/178274167-b5fcdeab-aed9-4f66-a8d9-462970423be0.png)
uhm are you sure you want the livery to look like this? The doors and windows r not in right place on the bottom fuselage texture, I think you have dragged it a little too down

**Comment by Ahnaf552** [comment]
> ![image](https://user-images.githubusercontent.com/105491758/178274167-b5fcdeab-aed9-4f66-a8d9-462970423be0.png) uhm are you sure you want the livery to look like this? The doors and windows r not in right place on the bottom fuselage texture, I think you have dragged it a little too down

OH HOLY COW WHAT THE HELL
Idk how that happen but its not supposed to be like that

**Comment by Ahnaf552** [comment]
I dont see anything wrong in the texture

**Comment by Ahnaf552** [comment]
The resulotion is the same right?
isnt it 2048px each side?? @Spice9

**Comment by Ahnaf552** [comment]
here have a 1 with the bottom a bit lower and if that dosent work then probably i sent you a png instead of jpg 
and will send you a jpg then

**Comment by Spice9** [comment]
mind resending it?

**Comment by Ahnaf552** [comment]
not at all
https://ibb.co/DzwB8XK
@Spice9
