### ISSUE TITLE
Mihin Lanka A320

### ISSUE THREAD

**Issue by SriLankanflyer** [Spice9/Geofs-Multiliveries#122]
https://ibb.co/6Ws5pyg So I will be making like every single airline in sri lanka I made sri lankan and mihin lanka so air ceylon and air lanka are left

**Comment by Spice9** [comment]
Interestingly I flew on this airline from Bahrain to Colombo and then from colombo to my home airport in India on SL Airlines. It sort of felt premium to me

**Comment by SriLankanflyer** [comment]
So um are you going to add them

**Comment by SriLankanflyer** [comment]
I  kind of need them tonight

**Comment by Spice9** [comment]
I'm currently doing its just taking a little time

**Comment by Spice9** [comment]
the thing is rather than uploading it directly I check if the livery correctly fits on things like fuselage,tail etc on the blender model and correct the using ms paint etc
