### ISSUE TITLE
Air Lanka A320

### ISSUE THREAD

**Issue by SriLankanflyer** [Spice9/Geofs-Multiliveries#124]
https://ibb.co/ThNF5T5 3/4 for the liveries of used to be sri lankan airlines except for sri lankan

**Comment by SriLankanflyer** [comment]
Btw there is a "Easter" egg

**Comment by Ahnaf552** [comment]
ya i  see it

**Comment by SriLankanflyer** [comment]
where cuz there is another one on the fuselage
