### ISSUE TITLE
Air Ceylon A320 

### ISSUE THREAD

**Issue by SriLankanflyer** [Spice9/Geofs-Multiliveries#125]
https://ibb.co/G0Jvy84  please add the Mihin Lanka , Air Lanka and this one as well 🥺🥺🥺🥺

**Comment by SriLankanflyer** [comment]
Um I actually need all of these now I have a little contest of who makes the best livery and im in it its not something like geofs people started  its some thing im doing with my friends a

**Comment by Spice9** [comment]
really sorry for being late but I added 3 of ur new liveries

**Comment by SriLankanflyer** [comment]
thanks
