### ISSUE TITLE
airGreenland A320neo (By BladesFlights-YT)

### ISSUE THREAD

**Issue by Coolio-Blade** [Spice9/Geofs-Multiliveries#126]
https://ibb.co/1dFdJ96

**Comment by Coolio-Blade** [comment]
Also just a question when anyone sees this, are virtual airlines allowed? (EG, can I make a livery/multiple liveries for a virtual airline and upload them here?)

**Comment by Spice9** [comment]
till the backend limit reaches for the a320neo it is, but I'll have to figure out a way to load it via links though. But the backend is getting filled more and more on the a320neo.

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/178269566-a1032b00-f3aa-434c-bd64-353172d5ef92.png)
damn

**Comment by Coolio-Blade** [comment]
ok cool, is the image file uploaded correctly or did I mess something up?

**Comment by Spice9** [comment]
it looks fine to me

**Comment by Spice9** [comment]
Also I prefer accepting virtual airlines (like peak air for example) than other fictional special livery of a real airline on the a320neo
