### ISSUE TITLE
MY PERSONAL LIVERY (FG AIRLINES)

### ISSUE THREAD

**Issue by FGAIRLINES** [Spice9/Geofs-Multiliveries#127]
The bottom isn't fixed, can you fix it?
I don't know how to do it.
This is the link
https://ibb.co/w6jdKJb

Thank you!!!

**Comment by FGAIRLINES** [comment]
Is the 787-9

**Comment by FGAIRLINES** [comment]
and can I have the map for P8 Poseidon?

**Comment by Ahnaf552** [comment]
Bro we dont invert it for you and if you use photopea then click on the layer (important to make a separate layer) then go into edit transform and flip horizontaly.

**Comment by Ahnaf552** [comment]
Just because your my G , I will invert it for you but this is the last time
https://ibb.co/TWXn0LB

**Comment by FGAIRLINES** [comment]
thank you very much and sorry so much, it will never happen again, it's just that I'm not very good with photopea.

**Comment by Ahnaf552** [comment]
Nah its fine . I dont mind and I suck at photopea too I just started using it like 4 days ago or something

**Comment by SriLankanflyer** [comment]
Also why haven't spice added this it's been 2 days

**Comment by iuhairways** [comment]
fictional i guess

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/178775040-62f5ed76-3fae-444b-b7be-3ade157b9d76.png)
well... not sure about this....

**Comment by FGAIRLINES** [comment]
Let it go for now, then I will send it back done right.
