### ISSUE TITLE
Is this the A320 map? I think i've got it.

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#13]
![image](https://user-images.githubusercontent.com/103064103/169350570-e88301c6-0890-4e36-b6d3-70b753eaa621.png)

**Comment by iuhairways** [comment]
Btw, i got it off of Rep Lit

**Comment by Spice9** [comment]
Nope its not I am actually making a a320neo now and will do the a320-214 later oh yeah I ran into some issues while making the egypt air livery and that cost me a lot of time I'm sorry hopefully it might I might provide it by today

**Comment by githubuser589** [comment]
> Nope its not I am actually making a a320neo now and will do the a320-214 later oh yeah I ran into some issues while making the egypt air livery and that cost me a lot of time I'm sorry hopefully it might I might provide it by today

nice, how long do you think the a320neo will take?

**Comment by githubuser589** [comment]
also, spice9, what's your timezone?

**Comment by Spice9** [comment]
I'm in India (gmt +5:30)

**Comment by Spice9** [comment]
> > Nope its not I am actually making a a320neo now and will do the a320-214 later oh yeah I ran into some issues while making the egypt air livery and that cost me a lot of time I'm sorry hopefully it might I might provide it by today
> 
> nice, how long do you think the a320neo will take?

Depends on whenever I would finish making liveries but I'll try to get it done by next friday

**Comment by Spice9** [comment]
I've made the a320neo map https://ibb.co/Dt0pct1
heres what the a320neo looks like if you're wondering https://ibb.co/PNTTjrf
this one looks quite complicated than the max 8 though
also I've put some instruction in it too clear them when making the livery

**Comment by githubuser589** [comment]
> I've made the a320neo map https://ibb.co/Dt0pct1 heres what the a320neo looks like if you're wondering https://ibb.co/PNTTjrf this one looks quite complicated than the max 8 though also I've put some instruction in it too clear them when making the livery

looks sick, cant wait!

**Comment by iuhairways** [comment]
easyJet neo pls 
and keep the easyJet ceo too so that there are 2 easyjet

**Comment by iuhairways** [comment]
@Spice9 how to make it like this on map?
![image](https://user-images.githubusercontent.com/103064103/169571966-88bd4f56-1ca1-4cbe-976c-13d65b5eeede.png)

**Comment by Spice9** [comment]
btw I'm making a 787-9 (IK theres already one in the game) this is what it looks like https://ibb.co/tpFRzFf
heres is the plain map https://ibb.co/rsBmbny if you're interested in making liveries. you may want to use these for reference
https://ibb.co/vZMcmHk
https://ibb.co/bsVM9zQ

here are the liveries that have been made so far:
Vistara 
Virgin Atlantic 
KLM 
EL AL 
F1 Etihad 
Qatar Airways
Qantas 
LATAM 
LOT
Turkish Airlines
Air Tahiti Nui 
Thai Airways
Korean Air
