### ISSUE TITLE
easyJet europe car update

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#131]
https://i.ibb.co/pzjpM3q/europcar-EZY-1.jpg

**Comment by iuhairways** [comment]
i need it ASAP

**Comment by iuhairways** [comment]
Dont ask why just add
but pls tell me when added like u normally do

**Comment by iuhairways** [comment]
@Spice9

**Comment by iuhairways** [comment]
qick

**Comment by iuhairways** [comment]
BY FRIDAY

**Comment by Spice9** [comment]
its there

**Comment by iuhairways** [comment]
ththx

**Comment by iuhairways** [comment]
> its there

nono  it is updated here

**Comment by iuhairways** [comment]
its different and better

**Comment by iuhairways** [comment]
because some bits on it arnt that good

**Comment by githubuser589** [comment]
> because some bits on it arnt that good

You should’ve double checked the original livery before submitting it…

**Comment by iuhairways** [comment]
no but i cant actually tell until its on it

**Comment by iuhairways** [comment]
@Spice9
