### ISSUE TITLE
737 AIR BALTIC

### ISSUE THREAD

**Issue by FGAIRLINES** [Spice9/Geofs-Multiliveries#132]
This is the link, the bottom of the aircraft is fixed!

https://ibb.co/3FKWNgh

Thank you!!!

**Comment by iuhairways** [comment]
cool!

**Comment by FGAIRLINES** [comment]
Thank you iuhairways!
Your easyjet livery is cool too!

**Comment by iuhairways** [comment]
thank you

**Comment by yvaristil** [comment]
This looks nice! I was literally just planning to make this tommorrow but you already did it

**Comment by Luca123144** [comment]
Nice livery! I'm planning to make an AereoItalia livery since the company just came out. Apparently you need to send the livery to Weebly.com and copy the link from there?

**Comment by FGAIRLINES** [comment]
I love Aeroitalia, it would make me happy if you did, you don't have to use Weebly.com but ibb.co, and thank you all for the compliments

**Comment by githubuser589** [comment]
The textures aren’t transparent which will make the livery look quite odd, nice livery though

**Comment by Spice9** [comment]
added

**Comment by Spice9** [comment]
@Luca123144 its not much problem for the max8 so you can send it here

**Comment by Luca123144** [comment]
Thanks!
