### ISSUE TITLE
Template

### ISSUE THREAD

**Issue by Luca123144** [Spice9/Geofs-Multiliveries#133]
I do not know where to find the template to make a livery as I would like to make a livery. A reply would be great!

**Comment by yvaristil** [comment]
A320-214 livery map:
https://ibb.co/ysRGhtT

**Comment by yvaristil** [comment]
A320neo livery map:
https://ibb.co/Dt0pct1

**Comment by yvaristil** [comment]
Boeing 787-9 livery map:
https://ibb.co/tpFRzFf

**Comment by yvaristil** [comment]
Credit goes to Spice9 for those, not me btw

**Comment by Luca123144** [comment]
Thanks very much but I need the Boeing 737 template. Is that possible?

**Comment by yvaristil** [comment]
I have no idea where the 737 Max template is lol. I think you should ask @Spice9

**Comment by iuhairways** [comment]
i got it

**Comment by iuhairways** [comment]
![image](https://user-images.githubusercontent.com/103064103/179074360-cece753f-6dae-4905-9a9a-6d217e40a395.png)

**Comment by Luca123144** [comment]
Thanks! Right now I am making an Aeroitalia livery!

**Comment by iuhairways** [comment]
cool

**Comment by SriLankanflyer** [comment]
Is there a319 map
