### ISSUE TITLE
Air Malta A320 (yes I know there are mistakes)

### ISSUE THREAD

**Issue by SriLankanflyer** [Spice9/Geofs-Multiliveries#138]
https://ibb.co/bKCjpQH (yes I know there are mistakes)  I need it by saturday btw

**Comment by SriLankanflyer** [comment]
And please let me know if something is wrong this is my first complex livery

**Comment by FGAIRLINES** [comment]
Beautiful

**Comment by githubuser589** [comment]
Some issues with your livery:

1: Your textures block out most of the windows

2: The textures on the back part of the fuselage are quite grainy

3: The colours of the tail and the rudder don’t match up

4: There is some weird blue mess around the tail section

5: Green dots are inaccurate

Would look quite nice though!

**Comment by Spice9** [comment]
I'm sorry to say this but the livery needs some improvements....

**Comment by SriLankanflyer** [comment]
It is hard to make with your thing cuz the tail section just hard to make no offense

**Comment by SriLankanflyer** [comment]
OK IM MAKING ANOTHER ONE (sorry for caps)
