### ISSUE TITLE
PROBLEM WITH 737 PAN AM

### ISSUE THREAD

**Issue by FGAIRLINES** [Spice9/Geofs-Multiliveries#140]
When I click on the aircraft I see Air Baltic livery...

It is strange

**Comment by Luca123144** [comment]
Same, I think Spice put the wrong link.

**Comment by Luca123144** [comment]
I found the problem
the code for Air Baltic
"name": "Boeing 737 Max 8 (Air Baltic) by FG Airlines",
  "livery": "150",
  "mptx": "https://www.geo-fs.com/backend/aircraft/repository/EL%20AL%20737-900_427352_2769/texture_150.jpg"

the code for PAN AM
"name": "Boeing 737 Max 8 (PANAM) by FG Airlines",
  "livery": "150",
  "mptx": "https://www.geo-fs.com/backend/aircraft/repository/EL%20AL%20737-900_427352_2769/texture_150.jpg"

You can see the texture in mptx are the same so the liveries are the same.
Hopefully Spice9 fixes it!

**Comment by Spice9** [comment]
fixed

**Comment by FGAIRLINES** [comment]
thank you!!!
