### ISSUE TITLE
Juneyao Chinese Silk Ribbon Livery 787-10

### ISSUE THREAD

**Issue by yvaristil** [Spice9/Geofs-Multiliveries#142]
I'm still stunned how beautiful this livery looks...
Livery: https://ibb.co/SPgGD8p
Tell me if there is something off so I can fix it :)

Thanks!

**Comment by Spice9** [comment]
thats the 787-10 map , here is the 787-9 map https://ibb.co/SJr94Lr. I'll add it for the 787-10 anyways

**Comment by yvaristil** [comment]
Oh sorry, they looked the exact same. It's also fine for the -10
Thx!

**Comment by Spice9** [comment]
added(for 787-10)
