### ISSUE TITLE
the liveries after air lanka dont work in 2.9 or 3.3

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#145]
idk why

**Comment by Spice9** [comment]
thats very strange....

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/179379159-99a6fbea-3474-4a2d-b7ca-97729d2bc4af.png)
Air Malta works for me but it took a while to load

**Comment by Spice9** [comment]
oh wait I basically forgot to upload the texture files of ur liveries, very sorry it should work now

**Comment by iuhairways** [comment]
ok
