### ISSUE TITLE
Livery not generating

### ISSUE THREAD

**Issue by yvaristil** [Spice9/Geofs-Multiliveries#146]
When you added my newest livery (Juneyao), I tried opening it in Geofs but it would load. I tried going to the source code and generating the link from there but I got a "404 Not Found nginx".
https://www.geo-fs.com/backend/aircraft/repository/Boeing%20787-10%20Dreamliner%20(Etihad)_427352_3180/texture_159.jpg
Could it be that the link in the code is wrong?

**Comment by Spice9** [comment]
I changed the name of it to "texture_159.6" and deleted "texture_159"
