### ISSUE TITLE
Aeroitalia BOEING 737

### ISSUE THREAD

**Issue by Luca123144** [Spice9/Geofs-Multiliveries#151]
https://ibb.co/1RkZzS9
Uploading the new airline Aeroitalia Boeing 737. Aeroitalia is a new airline made in 2022 based in Italy. Their livery looks alright so I decided to make it. Please upload this on the addon liveries as this livery took me days to make.
Thank you and hope you like it!

**Comment by Spice9** [comment]
added

**Comment by Luca123144** [comment]
Thanks so much!

**Comment by FGAIRLINES** [comment]
I am italian and I love this livery!!!

**Comment by Luca123144** [comment]
I am also Italian. This livery took me a few days to make. But it was worth
it. Glad you like it!
