### ISSUE TITLE
Nam Air a320neo livery

### ISSUE THREAD

**Issue by bajushd** [Spice9/Geofs-Multiliveries#152]
https://ibb.co/p1Kg736

**Comment by githubuser589** [comment]
Issues with your livery:

-The tail textures aren’t lined up with the template

-Your textures are covering some of the windows and doors

-The Nam Air logo on the fuselage looks like it’s going to overlap the cockpit windows

-You didn’t remove the text on the belly and engines 

-You have watermarks all over the tail section of your livery

-Some of your fuselage textures go into the winglet textures

-The resolution of your map looks too low

**Comment by Spice9** [comment]
I'm sorry to say this but it would be great if you would place NAM Air text on the bottom fuselage properly
