### ISSUE TITLE
Sriwijaya air Boeing 737 - 8 

### ISSUE THREAD

**Issue by bajushd** [Spice9/Geofs-Multiliveries#153]
https://ibb.co/xFHgmHY

**Comment by githubuser589** [comment]
Issues with your livery:

-You have watermarks on some of your fuselage textures

-Your tail textures aren’t aligned

-You didn’t remove the text on the engines and belly

-The map looks cropped

-It’s an a320neo livery, not a max 8 livery

**Comment by Spice9** [comment]
^^

**Comment by bajushd** [comment]
How do I prevent the writing/logo from covering the windows and doors? thanks....
