### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by CementAndRebar** [Spice9/Geofs-Multiliveries#157]
Why cant you save the livObj info in a separate file, and then call it in the code? And why cant you do a tampermonkey file too? 
If you want, you can give me perms, and i can do all this stuff for you. @Ariakim-Taiyo

**Comment by JadenAviation** [comment]
I think the code is updated every day so tampermonkey file is unnecessary

**Comment by CementAndRebar** [comment]
Cue the first part of my post

**Comment by Spice9** [comment]
@TotallyRealElonMusk Accept the perms I sent

**Comment by CementAndRebar** [comment]
Perfect, thanks! ill do this as soon as possible
