### ISSUE TITLE
Request to close 787-10 Air Vietnam

### ISSUE THREAD

**Issue by ThatOneBestDoggo** [Spice9/Geofs-Multiliveries#167]
So...... to give you backstory:
Air Vietnam was pretty much the South Vietnam's national airline until 1975.
The Boeing 787-10 was released...... in 2017.
42 years of total unrealisticness.
I thought you said no fictional liveries allowed?
This is realistic fiction. Would never exist though.
@Spice9 Please fix this. (also it's offending for the North Vietnamese ppl)

(edit: I found another issue: The Visit Vietnam Livery doesn't even exist)

**Comment by Spice9** [comment]
alright...

**Comment by ThatOneBestDoggo** [comment]
there's also a edit, check it out

**Comment by ThatOneBestDoggo** [comment]
@Spice9 
That's all I got to say

**Comment by JadenAviation** [comment]
Hmm, do you get offended by politics and your history with me?

**Comment by JadenAviation** [comment]
Bro, history is history, no one will care about the Republic Of Vietnam now because they ( the government of South Vietnam) are the loser in Vietnam War.  Next, I ended the nonsense argument with you so can you just let me have a life?

**Comment by ThatOneBestDoggo** [comment]
Uhh... what?
I thought that was over...
Your livery was just unrealistic. This is just my opinion. How the heck does a airline ending in 1975 get a plane that was released in 2017 and had a project that started in 2004. I'm about to go through a bug finding spree in this whole GeoFS Multilivery script. Again, I would want any livery closed if it's not realistic and is practically hilarious. Believe me, I would tell Spice9 to close down a A220 Vietnam Airlines Retro Livery. Stop making unrealistic liveries. If you don't have livery ideas, ask me. I've got a million ideas that I can't do.

**Comment by ThatOneBestDoggo** [comment]
smh...

**Comment by Spice9** [comment]
I might just create a dropdown to seperate fictional ones or make a new script for it except a very few. I might be very rude saying this but I prefer real ones or atleast the a320CEO livs on the neo or the 737ng livs on max, making the real liveries might be harder but I never expected people to submit fictional liveries when I allowed people to contribute liveries.  

The way I make liveries is actually different from what people usually do, ie my method requies softwares like sketchup and u need to do some adjusting in PS or if I'm lazy in powerepoint and paint. I will soon upload a tutorial on making liveries using my complicated that I hope people would find easier to do though that might require sketchup and PS like softwares

**Comment by ThatOneBestDoggo** [comment]
> I might just create a dropdown to seperate fictional ones or make a new script for it except a very few. I might be very rude saying this but I prefer real ones or atleast the a320CEO livs on the neo or the 737ng livs on max, making the real liveries might be harder but I never expected people to submit fictional liveries when I allowed people to contribute liveries.

I only prefer fictional liveries if they relate to GeoFS in some way. I don't want a Ryanair A320neo livery being made here because that's unrealistic. I agree that I prefer real liveries. For me, the only 2 fictional liveries that I don't mind are the GeoFS Air one and Shiba & Co one because someone's going to use that livery a lot.

> The way I make liveries is actually different from what people usually do, ie my method requies softwares like sketchup and u need to do some adjusting in PS or if I'm lazy in powerepoint and paint. I will soon upload a tutorial on making liveries using my complicated that I hope people would find easier to do though that might require sketchup and PS like softwares

I just copy the airplane format, put it in Paint 3d (bc that's the only software that's good and that i'm familliar with), grab a reference off of the internet, and start copying parts from the reference, and fixing a few things to make it fit. There's also a lot of easy real liveries. Right now I'm just searching for good liveries to make.

**Comment by iuhairways** [comment]
> I might just create a dropdown to seperate fictional ones or make a new script for it except a very few. I might be very rude saying this but I prefer real ones or atleast the a320CEO livs on the neo or the 737ng livs on max, making the real liveries might be harder but I never expected people to submit fictional liveries when I allowed people to contribute liveries.
> 
> The way I make liveries is actually different from what people usually do, ie my method requies softwares like sketchup and u need to do some adjusting in PS or if I'm lazy in powerepoint and paint. I will soon upload a tutorial on making liveries using my complicated that I hope people would find easier to do though that might require sketchup and PS like softwares

sketchup?

**Comment by ThatOneBestDoggo** [comment]
it's like a 3d modelling website

**Comment by iuhairways** [comment]
i know
