### ISSUE TITLE
Some Updates

### ISSUE THREAD

**Issue by Spice9** [Spice9/Geofs-Multiliveries#168]
* A220-300 is now compatible with the addon and all of its liveries should work.
* Elon Musk has made a Tampermonkey version of this addon , https://github.com/Spice9/Geofs-Multiliveries/blob/main/Tampermonkey%20version%20by%20Elon%20Musk/Instructions.md here are the instructions or you could watch this yt video I made https://www.youtube.com/watch?v=x38srVi19rc
* I'm restricting the fictions liveries that are being made for a320neo because the space in the backend might get filled up soon

**Comment by JadenAviation** [comment]
And my AirVietnam get removed :(

**Comment by iuhairways** [comment]
> * A220-300 is now compatible with the addon and all of its liveries should work.
> * Elon Musk has made a Tampermonkey version of this addon , https://github.com/Spice9/Geofs-Multiliveries/blob/main/Tampermonkey%20version%20by%20Elon%20Musk/Instructions.md here are the instructions or you could watch this yt video I made https://www.youtube.com/watch?v=x38srVi19rc
> * I'm restricting the fictions liveries that are being made for a320neo because the space in the backend might get filled up soon

Cool!

**Comment by ThatOneBestDoggo** [comment]
Restrict every fictional livery exept the GeoFS Air and those VA stuff

**Comment by ThatOneBestDoggo** [comment]
> And my AirVietnam get removed :(

because it was unrealistic damn it

**Comment by randomgeofsplayer** [comment]
glad to see some of my a220 liveries in there (breeze, air senegal, air manas, egyptair (in part) and maybe some KAL). thanks for this addon.
