### ISSUE TITLE
a-320 neo vietjet 

### ISSUE THREAD

**Issue by vietnam876** [Spice9/Geofs-Multiliveries#172]
https://ibb.co/48VJxyY

**Comment by githubuser589** [comment]
Issues:

-The engines look a bit messy

-Arial font…?

-Weird registration

-Guide text hasn’t been removed

**Comment by JadenAviation** [comment]
And I'm already made Vietjet A320neo livery tho :)

**Comment by vietnam876** [comment]
yea

**Comment by vietnam876** [comment]
u can made bamboo airways
