### ISSUE TITLE
2 more liveries that I think should be closed

### ISSUE THREAD

**Issue by ThatOneBestDoggo** [Spice9/Geofs-Multiliveries#175]
Those 2 liveries are the Australian Airlines and the Vist Vietnam (supposed to be visit vietnam but it was a typo)
They don't exist. Also looks like not a lot of people would use them. In my opinion, I think it should be closed.
[if these liveries are your only liveries, I will give you other livery ideas to do.]
@Spice9 Please respond.

**Comment by vietnam876** [comment]
why ?

**Comment by JadenAviation** [comment]
Ok, you want to close all of the fictional liveries that are not used by a lot of people right?

**Comment by ThatOneBestDoggo** [comment]
smh just make realistic liveries

**Comment by ThatOneBestDoggo** [comment]
>Ok, you want to close all of the fictional liveries that are not used by a lot of people right?

yes. absolutely so. fictional liveries are those liveries that are like a meh to me but if they're not realistic in any way then i would hate it

**Comment by ThatOneBestDoggo** [comment]
> why ?

oh yea, because:
1. i'm not familliar with them at all and i guess everyone exept the maker of the livery will also be like that
2. they're mostly from beginner livery makers who don't even know the concept of the liveries (minus jaden and the other vietnamese guy)
3. actual liveries have color tones that a avgeek can easily adjust their eyes to and actual liveries are complex, which gives them a nice form that other people will actually use.
oh yea, and also in the case of the 787-10 air vietnam, that's pretty much comparible to a easyjet 787-9. you can see where i'm going with this.

**Comment by ThatOneBestDoggo** [comment]
i hope that leaves yall with no answers

doggo out

**Comment by JadenAviation** [comment]
Hmm, quite an interesting opinion

**Comment by Lachy-your-local-aussie** [comment]
i made the livery as i use it nearly every day

**Comment by JadenAviation** [comment]
> i made the livery as i use it nearly every day

Legit
