### ISSUE TITLE
Air Macau A320neo

### ISSUE THREAD

**Issue by ThatOneBestDoggo** [Spice9/Geofs-Multiliveries#176]
https://ibb.co/P93THXv
Made by ThatOneBestDoggo.

**Comment by ThatOneBestDoggo** [comment]
@Spice9 oh yea, can i also contribute so that i can just check to see if there's unrealistic liveries and also if there's any mistakes
(please add this livery as well)

**Comment by Spice9** [comment]
added

**Comment by Spice9** [comment]
you had that gray border thing, I removed it though anyways not a bad livery

**Comment by ThatOneBestDoggo** [comment]
Hm.. gray border thing you say?

**Comment by ThatOneBestDoggo** [comment]
oh yea i did have a gray border thing
removing it now

**Comment by ThatOneBestDoggo** [comment]
how the heck did that gray border thing get here
https://media.discordapp.net/attachments/887224678660341770/1003292364086968460/unknown.png?width=619&height=616
it's at a lower quality but just try to get it in

**Comment by ThatOneBestDoggo** [comment]
@Spice9 add
where da issues

**Comment by ThatOneBestDoggo** [comment]
if that's not working, last ditch effort, just crop the one with the gray border

**Comment by Spice9** [comment]
I fixed it....

**Comment by ThatOneBestDoggo** [comment]
ok
is it in?
