### ISSUE TITLE
A319 Tigerair

### ISSUE THREAD

**Issue by JadenAviation** [Spice9/Geofs-Multiliveries#177]
https://ibb.co/GCkd3Tw

**Comment by ThatOneBestDoggo** [comment]
flip the text dam it

**Comment by JadenAviation** [comment]
shit forgot

**Comment by JadenAviation** [comment]
wait I think u can't flip the text because the other side is opposite:)-

**Comment by ThatOneBestDoggo** [comment]
oh yea
(don't say i'm stupid)
