### ISSUE TITLE
Delta A320neo

### ISSUE THREAD

**Issue by NavyNeo** [Spice9/Geofs-Multiliveries#179]
https://ibb.co/X8GFttG

**Comment by githubuser589** [comment]
Issues:

You didn’t paint the belly properly, 
The winglets are in the wrong colour
The Delta text looks too big
 You didn’t paint the engines
 

To top it all off, Delta doesn’t operate the a320neo, and I’m not sure if fictional liveries are allowed

**Comment by Spice9** [comment]
I would allow a delta livery since they have a320ceo but then again he needs to fix a few issues that you mentioned

**Comment by ThatOneBestDoggo** [comment]
> Issues:
> 
> You didn’t paint the belly properly, The winglets are in the wrong colour The Delta text looks too big You didn’t paint the engines
> 
> To top it all off, Delta doesn’t operate the a320neo, and I’m not sure if fictional liveries are allowed

damn you really are a delta geek aren't you

**Comment by ThatOneBestDoggo** [comment]
eh, delta operates the a320-200 

close enough

i mean the born in 2021 livery was a a320-214 to be exact but that was still added soooooo

just respect his work

doggo out
