### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by githubuser589** [Spice9/Geofs-Multiliveries#18]
![image](https://user-images.githubusercontent.com/99083788/169577985-536eaa57-1aa6-4f7c-846e-b3bc9d8f9881.png)

Do we fill this box in to make a zorro mask?

**Comment by iuhairways** [comment]
I guess

**Comment by iuhairways** [comment]
@Spice9

**Comment by githubuser589** [comment]
Also, how would I texture the flap fairings to make it look like this?
![image](https://user-images.githubusercontent.com/99083788/169606373-25448a7d-2871-4844-be1a-370d55889d3a.png)

**Comment by Spice9** [comment]
yes

**Comment by Spice9** [comment]
> Also, how would I texture the flap fairings to make it look like this? ![image](https://user-images.githubusercontent.com/99083788/169606373-25448a7d-2871-4844-be1a-370d55889d3a.png)

you need to fill the flap fairing thing in red https://ibb.co/JtjcW71
