### ISSUE TITLE
Good news!

### ISSUE THREAD

**Issue by Spice9** [Spice9/Geofs-Multiliveries#180]
The space issue probably wont be much of a problem as Ariakim has made it possible to load liveries via link. Fictional liveries to some extent may be allowed but I'm trying to make dropdown for the fictional ones but please put effort for making such liveries atleast rather than a plain shades with adverts and a text.

 But my no.1 priorities will be the real ones or the ceo and ng liveries on the neo and max respectively.

**Comment by Spice9** [comment]
Also if you're tired of copying the lengthy code use the tampermonkey version. I've made a tutorial on it https://www.youtube.com/watch?v=x38srVi19rc&t=3s

**Comment by ThatOneBestDoggo** [comment]
I think it'd be better to just ban fictional liveries exept those that are actually well made and not text, some logos and a flag. That's just not looking good.

**Comment by ThatOneBestDoggo** [comment]
Oh yeah; and liveries of airlines that don't own a plane should be banned too.
