### ISSUE TITLE
the A320neo EasyJet europcar is wrong link

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#183]
in elon's tamper monkey one it works because the link is https://www.geo-fs.com/backend/aircraft/repository/airbus a320-214 (Easyjet)_427352_2871/texture_135.6.jpg.
But in spice9's it doesnt work because the link is https://www.geo-fs.com/backend/aircraft/repository/airbus a320-214 (Easyjet)_427352_2871/texture_135.jpg which brings us to a 404 nginx page.
so if you can update then that would be cool. It is fixable by editing the code in the console but that isn't too simple.

**Comment by Spice9** [comment]
its fixed

**Comment by iuhairways** [comment]
okay

**Comment by iuhairways** [comment]
still broken
you put 136 instead of 135.6
