### ISSUE TITLE
doesn't work on 3.3 

### ISSUE THREAD

**Issue by ThatOneBestDoggo** [Spice9/Geofs-Multiliveries#184]
help please ;-;

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/183254991-ed71a756-1693-4121-be76-02b45a89b8e4.png)
works for me... you should try using the github version though

**Comment by iuhairways** [comment]
the berlin easyJet doesnt work in 3.3 though

**Comment by ThatOneBestDoggo** [comment]
HUH?
oh ok bc i use tampermonkey
