### ISSUE TITLE
why does it say ariways?

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#188]
![image](https://user-images.githubusercontent.com/103064103/183292579-e5e5df9b-a6a5-4bca-be13-2cd61b2a1bc6.png)

**Comment by Spice9** [comment]
oops that was a typo error

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/183299810-05732e22-98cd-47a6-8f57-4c822fa134e6.png)
uh...

**Comment by iuhairways** [comment]
o.o.o.o.o.o

**Comment by iuhairways** [comment]
try the air india or flynas aswell
~~or ask xavier for more space~~
