### ISSUE TITLE
Carribean 737MAX Issue

### ISSUE THREAD

**Issue by ThatOneBestDoggo** [Spice9/Geofs-Multiliveries#192]
the text on 1 side was backwards, so here's the new version: 
![image](https://user-images.githubusercontent.com/98545781/184070630-0084e62a-1718-4538-87b5-77c572eb0fc0.png)

**Comment by ThatOneBestDoggo** [comment]
@Spice9 uhh

**Comment by iuhairways** [comment]
it has my approval (i am da creator)
