### ISSUE TITLE
easyJet carrot A320neo

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#194]
https://i.ibb.co/9ybDwjg/carot.jpg

**Comment by githubuser589** [comment]
The “easyjet.com” text blocks out the windows and looks too big. There’s no engine details as well.

**Comment by iuhairways** [comment]
i forgot!!!
im so dumb i was very tired

**Comment by githubuser589** [comment]
it’s alright lol
