### ISSUE TITLE
Regarding the GeoFS Update:

### ISSUE THREAD

**Issue by Ariakim-Taiyo** [Spice9/Geofs-Multiliveries#195]
Most of you have probabnly noticed that geofs has officially updated to 3.3. While this is great for the sim as a whole, it has broken a bit of this addon, notably the loading functions. For the time being, legacy geofs is still functional. I will be working on rewriting the loading functions today/tomorrow and get everything working again.

Also, I'm probably going to be creating an alternative method for submissions, since the github issues page is meant for issues and not submissions lol. It will either be a website or an email method.

I'll make sure to update the TM version as well, and you'll likely see a lot of changes around the repo soon.

**Comment by iuhairways** [comment]
okay

**Comment by Ariakim-Taiyo** [comment]
Issue is now fixed. both 3.3 and 2.9 are functional

**Comment by iuhairways** [comment]
yaay
