### ISSUE TITLE
A.I A319 for the multiliveries 

### ISSUE THREAD

**Issue by SriLankanflyer** [Spice9/Geofs-Multiliveries#196]
https://ibb.co/LNMt1kn here is the link and I know I need to send it to Gt but I have sent it to him as well I am just putting it here cuz I want it to done and also because you are the author of this plugin and if I send it to both my chances of getting it in the plugin will increase

**Comment by ThatOneBestDoggo** [comment]
i'll send it to GT, fictional livery tho?

(still will send it)

**Comment by SriLankanflyer** [comment]
Thanks

**Comment by SriLankanflyer** [comment]
And did you send it

**Comment by ThatOneBestDoggo** [comment]
yea
