### ISSUE TITLE
A320 Neo VietNamairline 

### ISSUE THREAD

**Issue by hellochaocaccau** [Spice9/Geofs-Multiliveries#199]
https://i.imgur.com/E5leOlV.png

**Comment by ThatOneBestDoggo** [comment]
As of now, we don't submit liveries here. Instead, we do it in the new Discord server. Thanks!

**Comment by hellochaocaccau** [comment]
oh thank you

**Comment by hellochaocaccau** [comment]
where

**Comment by githubuser589** [comment]
https://discord.gg/GnU7kBcXtR
