### ISSUE TITLE
do you have a discord

### ISSUE THREAD

**Issue by Lachy-your-local-aussie** [Spice9/Geofs-Multiliveries#20]
i have an idea for an aircarft 

The E-7 wedgetail 

it would be as simple as putting the radar on the back of the P8 posiden
![e-7-wedgetail-770x385@2x](https://user-images.githubusercontent.com/99522179/169630061-a60b51a5-5dc0-459a-8d1e-90f04aef9615.jpg)

**Comment by iuhairways** [comment]
Isn't that harder than it looks?
