### ISSUE TITLE
Painting Dreamliners

### ISSUE THREAD

**Issue by airgeorge** [Spice9/Geofs-Multiliveries#201]
Hello there,I want to make a few paint schemes for the 787-10 and 787-9 Dreamliners.I was just wondering is there any specific template for them or do you use just the normal template?

**Comment by Spice9** [comment]
https://ibb.co/SJr94Lr 787-9
https://ibb.co/qdPPCst 787-10 
do note that there are a few differences though they look almost the same

**Comment by airgeorge** [comment]
Ok,thank you!
