### ISSUE TITLE
two liveries for A20N (CSN and CCA)

### ISSUE THREAD

**Issue by CSN1774** [Spice9/Geofs-Multiliveries#203]
![1661523276046](https://user-images.githubusercontent.com/112188625/186936924-76b064f4-9c59-430a-8152-22dd93d31168.png)

![1661524097876](https://user-images.githubusercontent.com/112188625/186936993-b5e6ce5f-d1e9-4e02-8284-ad7f043a66e2.png)

please add them to geofs! ;)

**Comment by githubuser589** [comment]
Issues with the China Southern livery:

-You didn’t remove the guide text
-You didn’t paint the engines 
-The China Southern text is in the wrong place
-You didn’t paint the winglets
-The cheat line is extended too far
-The cheat line is placed too high on the fuselage
-The cheat line is different on one side
-The tail logo is too small
-You didn’t flip the text on the bottom fuselage
-There’s no registration or aircraft designation on the fuselage

Issues with the Air China livery:

-The Air China decals on the fuselage are the wrong size and are in the wrong places
-You didn’t remove the guide text
-The cheat line is placed too low
-You didn’t paint the winglets
-There’s no registration on the fuselage 
-You didn’t paint the engines
-You didn’t flip the text on the bottom fuselage
-The tail logo is placed too far to the front

**Comment by Spice9** [comment]
I myself fixed like most a few with the CZ and Air China livery
https://raw.githubusercontent.com/Spice9/stuff2/main/texture_181.jpg
https://raw.githubusercontent.com/Spice9/stuff2/main/texture_180.jpg
