### ISSUE TITLE
A320Neo AirAsia X Solaire Resort & Casino

### ISSUE THREAD

**Issue by PilotKetchum2002** [Spice9/Geofs-Multiliveries#204]
https://i.postimg.cc/rmBtnsvR/Texture-77.jpg

**Comment by githubuser589** [comment]
Wow that looks cool, however some of the textures overlap each other and don’t allign

**Comment by Spice9** [comment]
bro u cant just cut and paste a paint kit texture and put it there that would mean copyright also its not even perfectly aligned and the livery seems incomplete
