### ISSUE TITLE
Hawaiian Airlines A320neo livery

### ISSUE THREAD

**Issue by BChang-3d** [Spice9/Geofs-Multiliveries#210]
https://ibb.co/mcHXVY1

**Comment by Spice9** [comment]
sorry but the livery is quite messed up

**Comment by BChang-3d** [comment]
oh gosh sorry about that. 
here's the new one :)

https://ibb.co/Z8G68Gz

**Comment by Aper583** [comment]
nice!

**Comment by BChang-3d** [comment]
and sorry. i forgot the rear doors 

https://ibb.co/myDRJJy heres the new one

**Comment by BChang-3d** [comment]
hello? spice? can I get an update on the status of this livery? If there is a problem, just let me know. I'll fix it.

**Comment by BChang-3d** [comment]
and updated 
https://ibb.co/WxGFTbS

**Comment by Spice9** [comment]
![Uploading image.png…]()
I just added it.

**Comment by BChang-3d** [comment]
ok thx
