### ISSUE TITLE
Important!

### ISSUE THREAD

**Issue by Aper583** [Spice9/Geofs-Multiliveries#213]
Can you teach Izem-bro-Emiz how to add flight in the multiveries?
Also after teaching him, please make him a contributor+.
He is killing me, please do it fast.

**Comment by GoldenFalcon54** [comment]
DO NOT MAKE HIM A CONTRIBUTER+, he will annoy us even more

**Comment by izem-bro-emiz** [comment]
i promise i will not

by the way

who messaged abot me

**Comment by izem-bro-emiz** [comment]
aper

**Comment by Aper583** [comment]
> DO NOT MAKE HIM A CONTRIBUTER+, he will annoy us even more

no you
