### ISSUE TITLE
Alaska Airlines A320neo livery

### ISSUE THREAD

**Issue by BChang-3d** [Spice9/Geofs-Multiliveries#215]
https://ibb.co/N1s5rL3

**Comment by BChang-3d** [comment]
please leave update status as you go.

**Comment by BChang-3d** [comment]
sorry i forgot some vital aspects let me edit it

**Comment by BChang-3d** [comment]
https://ibb.co/r6vzg7h 
here. I added the text logo and the tail-number
tell me if it needs anything

**Comment by BChang-3d** [comment]
wait let me fix the engine decals

**Comment by BChang-3d** [comment]
here
https://ibb.co/L98ZwdS

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/194737840-a8ff8902-edf9-49d6-a919-6195e4304cbe.png)
the livery is great but can you flip the alaska text on the bottom?

**Comment by BChang-3d** [comment]
oh yes. sorry about that

**Comment by BChang-3d** [comment]
[image: image.png] is this good or no?

**Comment by BChang-3d** [comment]
https://ibb.co/rdrrw58 

yes or no?

**Comment by Spice9** [comment]
![Uploading image.png…]()
just added it

**Comment by BChang-3d** [comment]
thank you.
