### ISSUE TITLE
A320neo livery submissions: TAP, SWISS, BA

### ISSUE THREAD

**Issue by githubuser589** [Spice9/Geofs-Multiliveries#22]
BA: https://ibb.co/xXWC7MY
SWISS: https://ibb.co/wMtjXk1
TAP: https://ibb.co/1q3kpmX

**Comment by Spice9** [comment]
Thank you very much btw I made an azul livery telling you incase you don't end up doing the same livery I am doing

**Comment by githubuser589** [comment]
alright np

**Comment by Spice9** [comment]
update on liveries done : 

Air India
Vistara
Air Asia
Air Astana
Iberia
VIVA
Qatar Airways
Air Seychelles
SAS
Cebu Pacific
LATAM

(again for the same reason)

**Comment by githubuser589** [comment]
> update on liveries done :
> 
> Air India Vistara Air Asia Air Astana Iberia VIVA Qatar Airways Air Seychelles SAS Cebu Pacific LATAM
> 
> (again for the same reason)

ah ok

**Comment by Spice9** [comment]
update on liveries done : 

Airbus house
Jetstar
Spirit
Air Cote di Ivore

**Comment by githubuser589** [comment]
> update on liveries done :
> 
> Airbus house Jetstar Spirit Air Cote di Ivore

noted
