### ISSUE TITLE
Alaska Airlines "Salmon thirty salmon" 737-800 livery

### ISSUE THREAD

**Issue by BChang-3d** [Spice9/Geofs-Multiliveries#220]

**Comment by BChang-3d** [comment]
https://ibb.co/dMDDSQt

let me know if it needs anything. also please update me on the status of the upload and stuff like that



*theres also a person in one of the windows.* :D

**Comment by BChang-3d** [comment]
![Alaska airlines salmon thirty salmon- 737-800 livery](https://user-images.githubusercontent.com/114553146/198856537-40f43f73-fd8d-446e-a499-cb307aae9910.jpg)

**Comment by Ariakim-Taiyo** [comment]
The registration is flipped improperly, and the texture itself appears to be a file from the internet pasted on top of the UV maps, and therefore it does not actually cover the texture properly. There is an issue with the seam on the top of the aircraft where the two halves are not going to line up correctly given the different upper portions you have provided. There are also no winglet textures provided here. You should consider fixing these issues first.

**Comment by BChang-3d** [comment]
alright, just scrap the thing. it would be too hard to draw it.

**Comment by femifadina** [comment]
thats wered
