### ISSUE TITLE
REQUEST : Batik Air Indonesia Airbus A320-214

### ISSUE THREAD

**Issue by AlexWins17** [Spice9/Geofs-Multiliveries#228]
![IMG_20221118_212717](https://user-images.githubusercontent.com/118540244/202728126-44e8243d-7d2b-4d29-8fa0-bb1886f6629d.jpg)
![IMG_20221118_212743](https://user-images.githubusercontent.com/118540244/202728145-ac097f70-1857-40df-9d0a-322c086adccf.jpg)
![IMG_20221118_212807](https://user-images.githubusercontent.com/118540244/202728227-17d11332-eb7e-403f-a131-360bf0e6fe54.jpg)

**Comment by CSN1774** [comment]
such a detailed livery template,is it suitable for the geofs a320-214?

**Comment by AlexWins17** [comment]
Yes, it's suitable for the Airbus A320-214

**Comment by AlexWins17** [comment]
It is suitable for the GeoFS A320-214. Are you going to put the livery in
GeoFS, and when will the livery be in GeoFS?

**Comment by githubuser589** [comment]
Where did you find this template?

**Comment by Ariakim-Taiyo** [comment]
This is not the GeoFS A320-214 template, so it will not fit on the aircraft. Also please reference the pinned issue.

**Comment by randomgeofsplayer** [comment]
Where did you get this map?

**Comment by AlexWins17** [comment]
Hi Spice 9, can you please do Batik Air Indonesia PK-LAH on the A320neo?
Thanks.
