### ISSUE TITLE
Clicking won't respond

### ISSUE THREAD

**Issue by Lucaalt43115** [Spice9/Geofs-Multiliveries#229]
Hello
When I try to click on a livery it doesn't seem to come up. Example = Corendon 737 -800 and Expedition Airlines 737-800.
Could you please fix this?
Thanks.
Luca D

**Comment by Ariakim-Taiyo** [comment]
Are there any errors in the console?

**Comment by Lucaalt43115** [comment]
![image](https://user-images.githubusercontent.com/106082543/208238113-6ad6849a-4894-465e-a10e-eaa20d61d058.png)
Clicking on an other livery works but the (Expedition Airlines) livery does not.

**Comment by GoldenFalcon54** [comment]
> ![image](https://user-images.githubusercontent.com/106082543/208238113-6ad6849a-4894-465e-a10e-eaa20d61d058.png) Clicking on an other livery works but the (Expedition Airlines) livery does not.

Hmm... I'll try to fix it and inform you if it's fixed

**Comment by GoldenFalcon54** [comment]
@Lucaalt43115 Fixed! Turns out the Expedition was 1028x1028 instead of 1024x1024 lol  and the corendon was 2048x2048
