### ISSUE TITLE
Custom liveries not working

### ISSUE THREAD

**Issue by thedolphinsfan1** [Spice9/Geofs-Multiliveries#238]

**Comment by thedolphinsfan1** [comment]
Sorry, wrong base map.

**Comment by thedolphinsfan1** [comment]
I made a mistake, so you don't have to regard this.

**Comment by thedolphinsfan1** [comment]
Ok so i paste this image:
![erj145](https://user-images.githubusercontent.com/111387425/216779126-ea5b0803-b31e-4367-a347-6866643697fc.png)
and comes out like this:
![Screenshot 2023-02-04 11 42 24 AM](https://user-images.githubusercontent.com/111387425/216779151-71f162fb-0c23-4882-ae58-e8891b4c2228.png)

**Comment by thedolphinsfan1** [comment]
also the 787x is screwy

**Comment by thedolphinsfan1** [comment]
and the a320neo

**Comment by thedolphinsfan1** [comment]
but the 737 max is fine

**Comment by Ariakim-Taiyo** [comment]
Please ensure that your livery textures are at 2k resolution (2048x2048 pixels).

**Comment by thedolphinsfan1** [comment]
Ok. Thank you. Is there a way that you guys could make it so people can submit liveries without being on the discord server? It is just because some people are very inappropriate in names and/or comments. Thank you.

Your past Multiliveries contributor,
Pawser Aviation

**Comment by Ariakim-Taiyo** [comment]
I can look into a separate method, I might integrate livery submissions with the plugin directly on the custom tab.

**Comment by thedolphinsfan1** [comment]
That is a great idea. I love the pop-up. So many things have been added since I left the Discord server. Could I get the 737-200 base map?

**Comment by Ariakim-Taiyo** [comment]
There is not actually a base map for the 732, so far everyone is just painting over the default texture. You can pull that directly from the geofs server.

**Comment by thedolphinsfan1** [comment]
> There is not actually a base map for the 732, so far everyone is just painting over the default texture. You can pull that directly from the geofs server.

How?
