### ISSUE TITLE
New A320 liv

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#24]
https://i.ibb.co/NjrY7Cj/A20-N-EWG2.jpg

**Comment by githubuser589** [comment]
you have to flip the text on the bottom fuselage texture

**Comment by iuhairways** [comment]
oh
that is simples tho

**Comment by iuhairways** [comment]
new one https://i.ibb.co/N7TrZrr/A20-N-EWG2-1.jpg
