### ISSUE TITLE
Alitalia A320N livery

### ISSUE THREAD

**Issue by FG3972** [Spice9/Geofs-Multiliveries#240]
https://ibb.co/dMV8FRh

**Comment by Ariakim-Taiyo** [comment]
Please do not submit liveries in the issues panel.

**Comment by FG3972** [comment]
Sorry for interrupting you, but i can't find the link of your discord, and
i am sorry for sending the alitalia A320N livery in the issues page

Il mer 15 feb 2023, 18:35 Ariakim-Taiyo ***@***.***> ha
scritto:
