### ISSUE TITLE
Boeing b787-9 Dreamliner Old Air Jamaica livery

### ISSUE THREAD

**Issue by MatthewaMorgan** [Spice9/Geofs-Multiliveries#242]
https://i.ibb.co/4t4QYXj/Old-Air-Jamaica-Boeing-b787-9-Dreamliner.jpg

**Comment by Ariakim-Taiyo** [comment]
> You have been blacklisted from submitting issues.
> Reason: Disregarding posted warnings regarding livery submissions.
