### ISSUE TITLE
Do you have the a320-214 map yet?

### ISSUE THREAD

**Issue by githubuser589** [Spice9/Geofs-Multiliveries#25]

**Comment by iuhairways** [comment]
pee

**Comment by githubuser589** [comment]
bruh

**Comment by Spice9** [comment]
nah. The thing is I have to make an entirely new map with 1024 X 1024 size since the current a320-214 textures are not in that size plus I have to map it all again in blender and I'm currently doing the a320neo...

**Comment by githubuser589** [comment]
kk
