### ISSUE TITLE
ERJ-145 Custom Liveries do not work

### ISSUE THREAD

**Issue by thedolphinsfan1** [Spice9/Geofs-Multiliveries#255]
I tried pasting my base map, but it came out small and showed the whole image on the nose.

**Comment by Ariakim-Taiyo** [comment]
Please ensure that your texture map uses the correct base map and is at 2k (2048x2048) resolution.
If the issue persists, please send a screenshot.

**Comment by thedolphinsfan1** [comment]
![image](https://github.com/Spice9/Geofs-Multiliveries/assets/111387425/f13cef14-e3af-4c13-ab7a-864d9f0d7606)
It didn't work
