### ISSUE TITLE
Hawaiian Airlines a320 

### ISSUE THREAD

**Issue by SoupGeoFs** [Spice9/Geofs-Multiliveries#266]
I play GeoFS alot and i record videos on youtube and tik tok please create hawaiian airlines please :)...!!! Thank you 
![Screenshot-2022-08-08-10 31 59-AM_copy_720x290_1](https://github.com/Spice9/Geofs-Multiliveries/assets/149280510/8dedea2a-726a-4d8a-ba11-6536b4a7265f)

**Comment by Ariakim-Taiyo** [comment]
Please do not submit / request liveries in the issues panel.
We have a Discord server for this purpose.
Repeat offenses will have you blacklisted from submitting any issues to this repo.
