### ISSUE TITLE
Multiliveries Not Working!

### ISSUE THREAD

**Issue by DidYouGetSniped** [Spice9/Geofs-Multiliveries#269]
When I click the button it goes to the webpage but shows the following message.

"Replit Legacy Hosting has migrated to Deployments
To host your application, use Replit Deployments."

Maybe you need to transition the project to Replit Deployments?

**Comment by damianryann** [comment]
I can confirm this also

**Comment by Ariakim-Taiyo** [comment]
I'll need to migrate away from Replit, since they no longer offer free web hosting and I'm not going to spend money on a project like this lol.
I'll look into a solution sometime soon. I need to prune the list of liveries anyway to make sure there's nothing broken or awful.

**Comment by damianryann** [comment]
@Ariakim-Taiyo things have been alright, might want to look into Digital Ocean they do free static hosting for apps I have one running now and its a simple Nextjs app. Or possibly github pages

**Comment by ghost** [comment]
it's not even showing up here

**Comment by Ariakim-Taiyo** [comment]
This issue should now be resolved. If it begins again, I'll look into moving the UI off of a website and directly into the plugin.
