### ISSUE TITLE
easyjet A320neo FIX

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#28]
https://i.ibb.co/qnKfhNs/mitoo.jpg

**Comment by Spice9** [comment]
uhm what exactly did you update though?

**Comment by iuhairways** [comment]
Where the bit is

**Comment by iuhairways** [comment]
the current liv is wrong

**Comment by iuhairways** [comment]
the orange bit not normally go on cockpit
