### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by githubuser589** [Spice9/Geofs-Multiliveries#37]
![image](https://user-images.githubusercontent.com/99083788/172025219-d9d05c53-7876-4ab3-8b0e-ce26b818e9c5.png)
![image](https://user-images.githubusercontent.com/99083788/172025238-a2de38e0-3776-48a8-964b-a9cbacdbd445.png)
Breaks and shows this after inserting code

**Comment by Spice9** [comment]
Oh no it seems like Xavier probably blocked this addon or so....

**Comment by Spice9** [comment]
I'll talk with Xavier

**Comment by Spice9** [comment]
Uh another silly mistake...

**Comment by Spice9** [comment]
Its fixed
