### ISSUE TITLE
where is the cockpit windows actually located on a320neo map?

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#39]

**Comment by Spice9** [comment]
https://ibb.co/QYNYDrZ it is located here

**Comment by iuhairways** [comment]
nonono here where
![Screenshot 2022-06-06 4 03 52 PM](https://user-images.githubusercontent.com/103064103/172188104-853d1496-4283-45d5-8e63-9a93f219eb90.png)

**Comment by Spice9** [comment]
https://ibb.co/Gcv3NXh

**Comment by iuhairways** [comment]
thx

**Comment by Spice9** [comment]
Updated it.I had to do some adjustments of my own but I guess it looks ok now
