### ISSUE TITLE
a320? b787?

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#4]
you colud make some a320 and b787 liveries

**Comment by iuhairways** [comment]
idk

**Comment by Spice9** [comment]
I am currently working on the a320 will do it on the 787 after the a320

**Comment by iuhairways** [comment]
ooh

**Comment by iuhairways** [comment]
can you do lufthansa and BA for A320?

**Comment by iuhairways** [comment]
@Spice9

**Comment by Lachy-your-local-aussie** [comment]
could you do jetstar australia?

**Comment by Spice9** [comment]
Jet star and LH are on the list....
I have like 35 liveries on the list for a320 but yeah thats gonna take a lot of time

**Comment by githubuser589** [comment]
> Jet star and LH are on the list.... I have like 35 liveries on the list for a320 but yeah thats gonna take a lot of time

May I ask what other liveries are on the list?

**Comment by Spice9** [comment]
> > Jet star and LH are on the list.... I have like 35 liveries on the list for a320 but yeah thats gonna take a lot of time
> 
> May I ask what other liveries are on the list?

1.Air India
2.Indigo
3.Vistara
4.Air Asia
5.Gulf Air
6.Kuwait Airways 
7.Flynas
8.Egypt Air 
9.Malta Airlines 
10.M.E.A
11.Scoot 
12.Jetstar
13.Sri Lankan Airlines
14.Cebu Pacific

15.Agean Airlines
16.Wizz Air
17.Lufthansa
18.Eurowings 
19.Iberia
20.Aer lingus
21.Airbus
22.Air Astana
23.SAS
24.Swiss

25.Frontier
26.Viva Air
27.Azul 
28.Latam
29.Avianca

30.Air Seychelles 
31.Air Cote d'ivore
32.Qatar Airways
33.TAP

So far I've only made Gulf Air,Kuwait Airways and Egypt Air and I am currently making Scoot. Some of these liveries may be cancelled if my mind changes or If I have difficulty with texturing

**Comment by Lachy-your-local-aussie** [comment]
could you add qantas link it should be quite easy 
![download](https://user-images.githubusercontent.com/99522179/169534956-ebebf524-7459-4d0c-b27b-6922e0ab8d50.jpeg)
