### ISSUE TITLE
B777-300ER

### ISSUE THREAD

**Issue by pepep132s** [Spice9/Geofs-Multiliveries#41]
Hey bro (Spice_9) pls create b777-300er.
I knew best livery : Emirates(pls try to make 50years or expo) , British Airways, KLM, United , American , Ukraine international , Qatar.
                                                                                                                                                 By pepep132s  (Discord: 9REALLY#5100)

**Comment by Spice9** [comment]
No. The 787-10 will be having an Emirates livery and some liveries u mention have been made

**Comment by pepep132s** [comment]
i said b777 because emirates don't have a b787

**Comment by Ariakim-Taiyo** [comment]
@pepep132s This plugin is incapable of modifying any planes that Spice9 did not create. the 777-300ER was made by LRX, and when i have tried to modify their liveries in the past, they pulled a jerk move and intentionally broke the plugin. 

Goes to show how childish the guy behind LRX really is.

**Comment by Spice9** [comment]
> i said b777 because emirates don't have a b787

They actually have an 787-10 on order or smth
