### ISSUE TITLE
New Livrey b737 max 8

### ISSUE THREAD

**Issue by pepep132s** [Spice9/Geofs-Multiliveries#42]
Add Ukraine International plsssssssssssssssssssssssss

**Comment by iuhairways** [comment]
I'll make it 😀

**Comment by pepep132s** [comment]
can u give me pls

**Comment by iuhairways** [comment]
Not done yet

**Comment by iuhairways** [comment]
'ere we go https://i.ibb.co/RzgJz47/UIA7378-M5.png

**Comment by iuhairways** [comment]
@pepep132s  it's done

**Comment by pepep132s** [comment]
how to inject this png

**Comment by iuhairways** [comment]
wdym
look at issue #43

**Comment by pepep132s** [comment]
i don't know how to use this livrey can u say me pls

**Comment by pepep132s** [comment]
do u speak russian

**Comment by Spice9** [comment]
> i don't know how to use this livrey can u say me pls

Its now available you should use the latest code https://github.com/Spice9/Geofs-Multiliveries/blob/main/Multiliveries.js
