### ISSUE TITLE
All the liveries made after ita airways dont work

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#45]

**Comment by iuhairways** [comment]
I click them but nothing happen

**Comment by Spice9** [comment]
were you using geofs 3.3?

**Comment by iuhairways** [comment]
yes

**Comment by Spice9** [comment]
ah no wonder why. The geofs 3.3 works on a copy of geofs 2.9 and Xavier has to update the 3.3 which is usually done in fridays

**Comment by iuhairways** [comment]
ok should it work now?
