### ISSUE TITLE
add S7 or РОССИЯ it's airlines just copy and paste for look the livrey

### ISSUE THREAD

**Issue by pepep132s** [Spice9/Geofs-Multiliveries#47]

**Comment by Spice9** [comment]
I'll add an aeroflot livery soon dude chill

**Comment by Spice9** [comment]
may I just ask one thing. are you from Russia or Ukraine?

**Comment by pepep132s** [comment]
Ukraine

**Comment by iuhairways** [comment]
i see

**Comment by githubuser589** [comment]
@pepep132s, could you be more specific? We need to know which aircraft you want it on.

**Comment by Spice9** [comment]
well, I'm gonna add it on the a320neo (altho AFL currently doesn't operate or have it) but there are pics of it in testing at airbus factory .

**Comment by Spice9** [comment]
Btw the aeroflot livery has been added
