### ISSUE TITLE
Livery Suggestion

### ISSUE THREAD

**Issue by githubuser589** [Spice9/Geofs-Multiliveries#5]
Hello, IF you are considering making A320 liveries, here is a couple of suggestions:

-Air Canada (ice blue)
-Azores Airlines

If you do plan on adding these, feel free to ask me for anything that's needed (e.g logos and hex codes).

Thanks!

**Comment by iuhairways** [comment]
um maybe airfrance too

**Comment by iuhairways** [comment]
> Hello, IF you are considering making A320 liveries, here is a couple of suggestions:
> 
> -Air Canada (ice blue) -Azores Airlines
> 
> If you do plan on adding these, feel free to ask me for anything that's needed (e.g logos and hex codes).
> 
> Thanks!

um theres a comment here  
![image](https://user-images.githubusercontent.com/103064103/168664037-60b91a2a-b3f7-434d-aa8b-46e36bcb9f22.png)

**Comment by iuhairways** [comment]
so yes
