### ISSUE TITLE
Code Isn't working on Any version

### ISSUE THREAD

**Issue by Lukeghrhgfhgh** [Spice9/Geofs-Multiliveries#56]
I was Getting on with the code,Except when i typed it in.It gave me An error and none of the liveries Popped up

I tried both 3.3 and 2.9,And both of them showed the same Error message (Uncaught SyntaxError: Identifier 'livObj' has already been declared)

**Comment by Spice9** [comment]
Its fixed, at this point I would recommend you to have a backup version of the code saved, I'm quite careless and makes some mistakes

**Comment by Lukeghrhgfhgh** [comment]
Welp,Sorry to say this again,Now every code is fixed,But the air india livery For some reason.Still doesn't work (Don't worry,I have made a backup of the code right now)

**Comment by Spice9** [comment]
I forgot to upload the texture, it should work now

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/173187044-06f21a1f-352d-4473-b8a4-ca18a0db7cee.png)
