### ISSUE TITLE
virgin antlantic 

### ISSUE THREAD

**Issue by pepep132s** [Spice9/Geofs-Multiliveries#57]
Can u give me new code because it's not working i use 3.3 and 2 9

**Comment by pepep132s** [comment]
i have this problem
![image](https://user-images.githubusercontent.com/106834226/173187575-e3a4f975-b55b-406f-afc7-5a385dc30b38.png)

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/173190270-f02cc316-ce73-4fc0-a4ad-7367e7a579ef.png)

**Comment by Spice9** [comment]
It works on the 2.9 but wont work on the 3.3 because the geofs 3.3 runs on a copy of geofs 2.9 and Xavier has to update it eventually and he normalldy does it on friday but these liveries were uploaded after Xavier updated it last time in friday so it won't really work

**Comment by pepep132s** [comment]
can u give code not' from code

**Comment by pepep132s** [comment]
i mean in my tab aircraft i didn't see the aircraft

**Comment by iuhairways** [comment]
odd

**Comment by pepep132s** [comment]
![image](https://user-images.githubusercontent.com/106834226/173195307-ca48b509-0dc3-40e4-8d17-8715a3b562ed.png)
