### ISSUE TITLE
Scoot airlines 787 (This was hard to do)

### ISSUE THREAD

**Issue by Lukeghrhgfhgh** [Spice9/Geofs-Multiliveries#59]
https://ibb.co/Nx0VYM4

This one was one of the harder ones that i had to do,All of the wavy lines and Text,it was hard to get them all of them in the right place

(The original scoot 787 Livery is on the 787-8,not the -10).

**Comment by Spice9** [comment]
Added

**Comment by Spice9** [comment]
Is the addon working now?
