### ISSUE TITLE
Is there any way I can create liveries for this plugin?

### ISSUE THREAD

**Issue by githubuser589** [Spice9/Geofs-Multiliveries#6]
Maybe I could have some bare maps to paint on or something?

**Comment by Spice9** [comment]
Hi,
so I've uploaded a bare map texture of the max 8 in here you can use that to make new liveries and then send it to me. Be careful 
with the winglets though.

here is the link : https://github.com/Spice9/Geofs-Multiliveries/commit/e47ad1955376563ba605bce5d364c115b955e4b4

**Comment by githubuser589** [comment]
Don't know which winglet texture is for what part, but I would like to see if this would work:

https://ibb.co/QnGmX7P

**Comment by githubuser589** [comment]
Also, do you have an A320 map? I'm planning to make liveries on it.

**Comment by Spice9** [comment]
well the thing is I haven't started doing liveries on the a320. I'm actually changing the a320-214 to a320neo(doing some changes to model now).... and I still haven't texture the 1st livery yet. maybe by tomorrow or day after tomorrow I would send you a bare map texture for the a320

**Comment by githubuser589** [comment]
Alright, take your time.

**Comment by Spice9** [comment]
there were a few incorrect texture mappings but I've fixed them the tail looks a little messy though but anyways thanks for your contribution. I've added it aswell https://github.com/Spice9/Geofs-Multiliveries/blob/main/Multiliveries.js

**Comment by iuhairways** [comment]
> well the thing is I haven't started doing liveries on the a320. I'm actually changing the a320-214 to a320neo(doing some changes to model now).... and I still haven't texture the 1st livery yet. maybe by tomorrow or day after tomorrow I would send you a bare map texture for the a320

neo? why don't you keep 214 and add neo aswell 
also pls keep easyjet

**Comment by iuhairways** [comment]
also 
why is ethopian on it

> Hi, so I've uploaded a bare map texture of the max 8 in here you can use that to make new liveries and then send it to me. Be careful with the winglets though.
> 
> here is the link : [e47ad19](https://github.com/Spice9/Geofs-Multiliveries/commit/e47ad1955376563ba605bce5d364c115b955e4b4)

**Comment by Spice9** [comment]
I am keeping 1 a320-214

**Comment by Spice9** [comment]
I am keeping 1 a320-214

**Comment by Spice9** [comment]
winglet map : https://ibb.co/tPp6pJS
