### ISSUE TITLE
New livery ideas

### ISSUE THREAD

**Issue by theguyonthenet** [Spice9/Geofs-Multiliveries#62]
For the 737 Max:

- Fiji Airways
- Virgin Australia
- Southwest
- Copa Airlines
- Singapore
- Korean
- Gol

For the A320neo:

- Air New Zealand
- Air Calin
- Aer Lingus
- Swiss
- JetBlue
- Avianca
- United
- Delta
- American

For the 787-10

- Air New Zealand
- Singapore
- Qatar
- Qantas
- Air Tahiti Nui
- LOT
- Air Canada
- KLM
- China Southern

I know some of these might not be realistic or possible, but they are just suggestions. But that should keep you guys busy for a while.

**Comment by iuhairways** [comment]
swiss is already on

**Comment by theguyonthenet** [comment]
Oh yes, sorry I didn't see it when I was making the list

**Comment by iuhairways** [comment]
ill do Aer lingus and united later

**Comment by githubuser589** [comment]
I will definiently do China Southern and Air Canada for the 787-9, thanks for the suggestions!

**Comment by Spice9** [comment]
lets not have high expectaion for the 787-9 because LRX doesn't seem to be that happy
![image](https://user-images.githubusercontent.com/105491758/173237413-32b7d9c7-d5bd-439e-846c-6fe1b7bd84f7.png)

**Comment by iuhairways** [comment]
keep 10 cuz then we got all 787 types

**Comment by Spice9** [comment]
I won't remmove the -10

**Comment by iuhairways** [comment]
oh ok
then we got a good type of 787-9
LRx is qite bad
