### ISSUE TITLE
Lufthansa 787 livery

### ISSUE THREAD

**Issue by Lukeghrhgfhgh** [Spice9/Geofs-Multiliveries#66]
https://ibb.co/BjNpfsW

**Comment by Spice9** [comment]
sorry for being inactive but I've added both of ur liveries

**Comment by iuhairways** [comment]
not that it is operated but ok noice

**Comment by Lukeghrhgfhgh** [comment]
I mean,I did that Before Spice9 Released his 787-9,So i had to work On the Only 787 He had before then,Which turned out to be the 787-10
