### ISSUE TITLE
Bro make b777-300 ER

### ISSUE THREAD

**Issue by pepep132s** [Spice9/Geofs-Multiliveries#71]
Pls

**Comment by Lukeghrhgfhgh** [comment]
As in Liveries for The already existing or Make a New 777-300ER out of Scratch?

Because if you mean the first one,The problem is LRX doesn't quite like When people Make stuff for his Planes and will Intentionally Mess something up to ruin that Thing

**Comment by pepep132s** [comment]
Make a new
