### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by theguyonthenet** [Spice9/Geofs-Multiliveries#73]
So how does it go with accessing the NEW A319's and the 787-9's

**Comment by Spice9** [comment]
wdym. Did you mean the plain map textures for those planes? I'm currently making a plain map for 789

**Comment by theguyonthenet** [comment]
So, Are you making your own version of the A319 & 787-9?

**Comment by iuhairways** [comment]
there is spice9 7879
but Gt A319
