### ISSUE TITLE
Lufthansa 787-9

### ISSUE THREAD

**Issue by Lukeghrhgfhgh** [Spice9/Geofs-Multiliveries#75]
https://ibb.co/5xZGvMR

Now On the Right version of the Lufthansa 787

**Comment by iuhairways** [comment]
Do lufthansa even have a 787?

**Comment by Lukeghrhgfhgh** [comment]
Yes,they ordered the -9 Version,

**Comment by Spice9** [comment]
Im very sorry for the delay but its now added.
