### ISSUE TITLE
B777

### ISSUE THREAD

**Issue by pepep132s** [Spice9/Geofs-Multiliveries#77]
MAke A NEW b777 PLS I LOVE U

**Comment by Spice9** [comment]
No.

**Comment by pepep132s** [comment]
I'AM GAY

**Comment by pepep132s** [comment]
I WANNA WITH U JAGA JAGA

**Comment by pepep132s** [comment]
MAKE b777 OR LIVREY FOR LRX b777

**Comment by githubuser589** [comment]
> MAKE b777 OR LIVREY FOR LRX b777

If you keep acting like this, you will most likely be blocked and ignored, so stop.

**Comment by Spice9** [comment]
Stop this nonsense please I hope you understand that I just wont make another 777.

**Comment by iuhairways** [comment]
spice wont make it
