### ISSUE TITLE
787-9 "Problem"

### ISSUE THREAD

**Issue by Lukeghrhgfhgh** [Spice9/Geofs-Multiliveries#78]
So Some People are saying that There can only be 1 787-9 in geoFS.And they're saying that LRX will get you in trouble,Can you confirm that LRX Will not get you in trouble?

**Comment by Spice9** [comment]
well, he has acknowledged that my 787-9 is there in geofs but thats not what he has problem with now . I have asked him if its ok to make another 787-9 but he didn't say any thing I even asked Xavier as well but he too didn't say anything. Right now he has a problem with my 789 speculating that I stole his fuselage model of his 787-9 and no I did not steal his 787-9 fuselage model or so. I don't know if hes trying to say that he is not happy with my 787-9 in the screenshot below, also did LRX say anything opposing about my 787-9 in his server ? Just wanted to know. 
![image](https://user-images.githubusercontent.com/105491758/174598839-13247e7b-86b1-4447-a738-7684400f38ec.png)

**Comment by Lukeghrhgfhgh** [comment]
Umm,I'm not In his server,But hopefully this Doesn't end with you Having to Take down your 787-9

**Comment by Spice9** [comment]
can I take a look at screenshots saying there can only be 1 787-9?

**Comment by Lukeghrhgfhgh** [comment]
Well it's Not really that phrase,But its similar
![Z5](https://user-images.githubusercontent.com/99502913/174603788-6614de12-e31a-48c5-95cf-3b9176dd1617.PNG)
![z6](https://user-images.githubusercontent.com/99502913/174603852-85245967-a93a-4e8c-8558-2c65c262d5f7.png)
