### ISSUE TITLE
My Comair livery

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#8]
@Spice9 could you add this:
(https://i.ibb.co/mDFx6wF/Comair-737-MAX.png)
also can you put in wing lets, they look like this:
![image](https://user-images.githubusercontent.com/103064103/168890374-c358d069-d05c-4c95-9399-bff6361dba5e.png)

**Comment by Spice9** [comment]
I've added the com air livery aswell. Thank  your for your contribution

**Comment by Spice9** [comment]
ok so here is the winglet map https://ibb.co/tPp6pJS
