### ISSUE TITLE
New Liveries not working

### ISSUE THREAD

**Issue by theguyonthenet** [Spice9/Geofs-Multiliveries#80]
every time there are new liveries are added i can't get it to work including the 787-9 and the A319, but the old ones still work when I load the code

**Comment by Spice9** [comment]
you must be using geofs 3.3 right? The thing is the geofs 3.3 runs on a copy of geofs 2.9 and Xavier has to update it eventually and he usually does it on fridays. The textures I uploaded after last friday are not there in geofs 3.3's backend so yeah...

**Comment by theguyonthenet** [comment]
oh ok, so it should be sorted by the end of the week. and yes, I am using 3.3

**Comment by iuhairways** [comment]
actually, Xavier didmt update it last friday
