### ISSUE TITLE
New A320neo livery

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#82]
https://i.ibb.co/7n7m6x7/GeoA30.jpg

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/175796832-d5fc4763-ccf8-4f37-9403-819ab10458f6.png)
the tail-fuselage part seems to be flipped the wrong way or I'm not sure if this the way you wanted it....

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/175796857-fdc39e2d-aaa9-4fd0-b819-067a21e42bd9.png)

Also one thing its the text that only needs to be flipped no need of logos or other stuff

**Comment by iuhairways** [comment]
i dont mind
