### ISSUE TITLE
IUH Airways A320neo livery

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#89]
https://i.ibb.co/w05Hs8B/iuha320.jpg

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/175937912-9e1211a4-0648-4fa5-8a36-976d46af2c13.png)
orange racoon mask?

**Comment by Spice9** [comment]
added a few of ur liveries btw really sorry for the delay

**Comment by iuhairways** [comment]
> ![image](https://user-images.githubusercontent.com/105491758/175937912-9e1211a4-0648-4fa5-8a36-976d46af2c13.png) orange racoon mask?

yup
