### ISSUE TITLE
Airbus A320Neo livery G-FS TimeLapse

### ISSUE THREAD

**Issue by Computer55x** [Spice9/Geofs-Multiliveries#91]
A friend want a livery to his name. Please can u add it ? Here is the image https://ibb.co/r6ndrqs 
Please mention my callsign in the livery title
CallSign : Pilot45

**Comment by iuhairways** [comment]
ooh hiPilot45

**Comment by Spice9** [comment]
I'm very sorry but the thing is the space in the backend of the a320neo is getting filled up (almost near the 10 mb limit), I've tried to make the addon work where the texture can be loaded via a raw.github or edit.previewmysite link but haven't worked. I'll try talking to Ariakim if he could figure things out, I am also thinking about making a seperate code for fictional liveries as I prioritize the real ones in the main code. I had a powercut today so I wasn't able to do much work on the addon and yesterday I quite wasted time figuring out with the thing I mention earlier, right now I'm just adding liveries that have been sent

**Comment by Spice9** [comment]
![image](https://user-images.githubusercontent.com/105491758/175939150-71131716-a670-4795-9ed6-7e6a4e905a6e.png)
would you mind re making the livery? there are certain parts of the textures that are not there in yours

**Comment by Spice9** [comment]
like those 3 colour shades between the engines

**Comment by Computer55x** [comment]
I thinked that we need to delete it
