### ISSUE TITLE
Spice_9 when will you add the A320-214 to the Multi Liveries

### ISSUE THREAD

**Issue by iuhairways** [Spice9/Geofs-Multiliveries#92]

**Comment by Ariakim-Taiyo** [comment]
As you may have heard in the GeoFS Extras server, the -214 is being remade by me and a X-Plane 11 dev.

**Comment by iuhairways** [comment]
oh
can you keep the same map so that my livs are still working?

**Comment by githubuser589** [comment]
> oh can you keep the same map so that my livs are still working?

I don't think that's how it works

**Comment by iuhairways** [comment]
hmm
but it is annoying

**Comment by githubuser589** [comment]
> hmm but it is annoying

It probably won't be that much of a hassle as you already have the decals anyways.

**Comment by iuhairways** [comment]
i suppose
