### ISSUE TITLE
NEW UPLOAD INSTRUCTIONS

### ISSUE THREAD

**Issue by Ariakim-Taiyo** [Spice9/Geofs-Multiliveries#94]
**Due to the current issue with the geofs backend slots being filled up with livery files, here are some new instructions for contributing to the project:**

1: Create your liveries in the same manner,
2: Instead of sending the image file for upload, you will need to do the following:
> Go to Weebly.com and create a website it doesn't have to be anything fancy, just somewhere to store files.)
> Edit the site and add in some file objects, and upload your livery to the file.
> Once it uploads, click on the download link and copy the URL.
> Make sure the url begins with "editmysite" and not "weebly", otherwise it won't work due to CORS restrictions.
> Send the link in a new issue and we will implement it through that link.

Thank you!

**Comment by iuhairways** [comment]
will ibb work?

**Comment by iuhairways** [comment]
https://i.ibb.co

**Comment by iuhairways** [comment]
?

**Comment by Spice9** [comment]
No sadly, You would either need a raw.github link or a edit.previewmysite link , weebly in my opinion would be a better option for that since you wont need to download github desktop for raw.github link .

**Comment by iuhairways** [comment]
oh

**Comment by iuhairways** [comment]
is this only for A320neo?

**Comment by iuhairways** [comment]
How do you use editmysite.com

**Comment by iuhairways** [comment]
?
HOW

**Comment by Ahnaf552** [comment]
What if we only had 1 website and we all stored it there.
It would make it easier for everyone.
:)

**Comment by Ahnaf552** [comment]
for example if i open up 1.
and you all send it to through email and i put it up .
Then Ariakim or Spice9 would take it from just 1 place
And if that fills up we can make another website

**Comment by Ahnaf552** [comment]
or why dont Ariakim Taiyo or Spice 9 open up a website

**Comment by Ahnaf552** [comment]
ITS TELLING ME I HAVE TO PAY MONEY???

**Comment by Ahnaf552** [comment]
OHHHHH
the backend at geo-fs 
i thought you were talking about different backend
why cant we just create another user for geo-fs then shouldnt we have that one
and exactly how many backend slots do we have remaining @Spice9

**Comment by Khangkha** [comment]
https://ibb.co/T43nhsF can i use this, cause in my country they banned weebly ;(

**Comment by WsnFu** [comment]
Hey there @Spice9 or @Ariakim-Taiyo . It's me, WsnFu. I wanna know how can I create a weebly website for free cuz apparently I need to pay for a website or idk... would someone please tell me what I should do so I can fit the requirements while not paying for a site? Thanks.

**Comment by Ariakim-Taiyo** [comment]
@WsnFu Weebly websites are free, you just have to create an account. then you'll get one free website, albiet slightly limited in functionality.

**Comment by WsnFu** [comment]
ok thanks man, I'll try.

**Comment by WsnFu** [comment]
Also, @Ariakim-Taiyo , I'd like to know if you have the blank templates for the Boeing 787-9? And maybe the 737 Max as well? Thank you so much!!!

**Comment by iuhairways** [comment]
but editmysit dosnt work

**Comment by Luca123144** [comment]
Help
